version: "3.1"

services:
  postgres:
    image: postgres:10
    container_name: graphql_chat_app_db
    ports:
      - 5440:5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatapp
    volumes:
      - graphql_chat_app:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: graphql_chat_app_redis
    ports:
      - 6379:6379
    restart: always

volumes:
  graphql_chat_app:
