version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: graphql_chat_app_db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatapp
    volumes:
      - graphql_chat_app:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: graphql_chat_app_redis
    ports:
      - "6378:6378"


volumes:
  graphql_chat_app:
